const cifras = [
  { nome: "1 - Chuvas de Graça", arquivo: "001-chuvas.html" },
  { nome: "2 - Saudosa Lembrança", arquivo: "002-saudosa.html" },
  { nome: "3 - Plena Paz", arquivo: "003-plena.html" },
  { nome: "4 - Deus Velará Por Ti", arquivo: "004-deusvelaraporti.html"},
  { nome: "5 - Ó Desce Fogo Santo", arquivo: "005-odescefogosanto.html"},
  { nome: "6 - Na Maldição da Cruz", arquivo: "006-namaldicaodacruz.html"},
  { nome: "8 - Cristo, O Fiel Amigo", arquivo: "008-ofielamigo.html" },
  { nome: "15 - Conversão", arquivo: "015-conversão.html" },
  { nome: "36 - O Exilado", arquivo: "036-oexilado.html" },
  { nome: "39 - Alvo Mais Que A Neve", arquivo: "039-alvo.html" },
  { nome: "77 - Guarda o Contato", arquivo: "077-guardaocontato.html" },
  { nome: "84 - O Grande Eu Sou", arquivo: "084-ograndeeusou.html"},
  { nome: "88 - Revela Nós Senhor", arquivo: "088-revelanossenhor.html" },
  { nome: "89 - Sublime e Grande Amor", arquivo: "089-sublimeegrandeamor.html" },
  { nome: "107 - Firme Nas Promessas", arquivo: "107-firmenaspromessas.html" },
  { nome: "115 - Trabalhai E Orai", arquivo: "115-trabalhai.html" },
  { nome: "127 - O Senhor e Da Ceifa Chama", arquivo: "127-osenhordaceifachama.html" },
  { nome: "151 - Fala Jesus Querido", arquivo: "151-falajesus.html" },
  { nome: "169 - Oh! Jesus Me Ama", arquivo: "169-jesusmeama.html" },
  { nome: "186 - De Valor Em Valor", arquivo: "186-devaloremvalor" },
  { nome: "187 - Mais Perto Quero Estar", arquivo: "187-maisperto.html" },
  { nome: "193 - A Alma Abatida", arquivo: "193-almaabatida.html" },
  { nome: "210 - Fala Fala Senhor", arquivo: "201-falafalasenhor.html" },
  { nome: "212 - Os Guerreiros Se Preparam", arquivo: "212-osguerreiros.html" },
  { nome: "224 - É Tempo De Segar", arquivo: "224-etempodesegar.html" },
  { nome: "225 - Sê Valente", arquivo: "225-sevalente.html"},
  { nome: "243 - Ao Abrir O Culto", arquivo: "224-aoabriroculto.html" },
  { nome: "243 - Ao Abrir O Culto", arquivo: "291-rudecruz.html" },
  { nome: "300 - Nossa Esperança", arquivo: "300-nossaesperança" },
  { nome: "301 - Vem Cear", arquivo: "301-vemcear.html" },
  { nome: "304 - A Face Adorada De Jesus", arquivo: "304-afaceadorada.html" },
  { nome: "305 - Campeões Da Luz", arquivo: "305-campeoesdaluz.html" },
  { nome: "422 - No Céu Não Entra Pecado", arquivo: "422-noceunaoentrapecado.html"},
  { nome: "442 - Breve Verei O Bom Jesus", arquivo: "442-breveverei.html" },
  { nome: "467 - Sobre As Ondas Do Mar", arquivo: "467-sobreasondas.html" },
  { nome: "525 - Vencendo Vem Jesus", arquivo: "525-vencendovemjesus.html" },
  { nome: "526 - Grandioso És Tu", arquivo: "526-grandiosoestu.html"},
  { nome: "545 - Porque Ele Vive", arquivo: "545-porqueelevive.html" },
  { nome: "547 - O Rei Está Voltando", arquivo: "547-oreiestavoltando.html" },
  { nome: "570 - A Última Hora", arquivo: "570-aultimahora.html" },
  // { nome: "", arquivo: ""},

  // Adicione outras cifras aqui
];
